In [1]:
#kütüphane ekleme
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#veri yükleme
data=pd.read_csv("C:/Users/bedir/Downloads/Churn_Modelling.csv")
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
#veriyi bölme
X=data.iloc[:,3:13].values
y=data[["Exited"]].values

In [9]:
#encoding Kategorik ==> Numeric
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

X[:,1] = le.fit_transform(X[:,1])

le2 =preprocessing.LabelEncoder()

X[:,2] = le2.fit_transform(X[:,2])

from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer

ohe = ColumnTransformer([("ohe", OneHotEncoder(dtype=float),[1])],
remainder="passthrough"

)

X= ohe.fit_transform(X)

X = X[:,1:]

X

array([[0.0, 0.0, 228, ..., 1, 1, 101348.88],
       [1.0, 0.0, 217, ..., 0, 1, 112542.58],
       [0.0, 0.0, 111, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 318, ..., 0, 1, 42085.58],
       [0.0, 1.0, 381, ..., 1, 0, 92888.52],
       [0.0, 0.0, 401, ..., 1, 0, 38190.78]], dtype=object)

In [13]:
# eğitim test ayrımı
from sklearn.model_selection import train_test_split 
x_train, x_test,y_train,y_test = train_test_split(X,y,test_size=0.33, random_state=0)

In [15]:
#standartizasyon
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train = sc.fit_transform(x_train)

X_test = sc.fit_transform(x_test)

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [23]:
classifier=Sequential()


classifier.add(Dense(units=6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))
classifier.add(Dense(units=6, kernel_initializer = "uniform", activation = "relu"))
classifier.add(Dense(units=1, kernel_initializer = "uniform", activation = "sigmoid"))
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train,y_train,epochs=50)

y_pred=classifier.predict(X_test)

Epoch 1/50
210/210 [==============================] - 1s 2ms/step - loss: 0.5974 - accuracy: 0.7961
Epoch 2/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4373 - accuracy: 0.7979
Epoch 3/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4290 - accuracy: 0.7979
Epoch 4/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4250 - accuracy: 0.7979
Epoch 5/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4214 - accuracy: 0.7979
Epoch 6/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4180 - accuracy: 0.8125
Epoch 7/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4149 - accuracy: 0.8255
Epoch 8/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4122 - accuracy: 0.8294
Epoch 9/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8310
Epoch 10/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4077 - accuracy: 0.8319
Epoch 11/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8342
Epoch 12/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8336
Epoch 13/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8333
Epoch 14/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8349
Epoch 15/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4015 - accuracy: 0.8354
Epoch 16/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4010 - accuracy: 0.8358
Epoch 17/50
210/210 [==============================] - 0s 2ms/step - loss: 0.4004 - accuracy: 0.8361
Epoch 18/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3999 - accuracy: 0.8348
Epoch 19/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8366
Epoch 20/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3987 - accuracy: 0.8357
Epoch 21/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3985 - accuracy: 0.8363
Epoch 22/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3977 - accuracy: 0.8355
Epoch 23/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3978 - accuracy: 0.8355
Epoch 24/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3970 - accuracy: 0.8352
Epoch 25/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.8373
Epoch 26/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3966 - accuracy: 0.8354
Epoch 27/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3960 - accuracy: 0.8370
Epoch 28/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3957 - accuracy: 0.8364
Epoch 29/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3958 - accuracy: 0.8345
Epoch 30/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3954 - accuracy: 0.8372
Epoch 31/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3953 - accuracy: 0.8363
Epoch 32/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3954 - accuracy: 0.8361
Epoch 33/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3953 - accuracy: 0.8355
Epoch 34/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3950 - accuracy: 0.8358
Epoch 35/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3951 - accuracy: 0.8361
Epoch 36/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3948 - accuracy: 0.8358
Epoch 37/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3946 - accuracy: 0.8360
Epoch 38/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3947 - accuracy: 0.8378
Epoch 39/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3944 - accuracy: 0.8361
Epoch 40/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3944 - accuracy: 0.8372
Epoch 41/50
210/210 [==============================] - 0s 1ms/step - loss: 0.3946 - accuracy: 0.8355
Epoch 42/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3943 - accuracy: 0.8376
Epoch 43/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3943 - accuracy: 0.8354
Epoch 44/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3945 - accuracy: 0.8360
Epoch 45/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3941 - accuracy: 0.8358
Epoch 46/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3940 - accuracy: 0.8378
Epoch 47/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3937 - accuracy: 0.8352
Epoch 48/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3939 - accuracy: 0.8369
Epoch 49/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3937 - accuracy: 0.8369
Epoch 50/50
210/210 [==============================] - 0s 2ms/step - loss: 0.3939 - accuracy: 0.8370
104/104 [==============================] - 0s 2ms/step

In [25]:
y_pred=(y_pred>0.5)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[2543,   74],
       [ 461,  222]], dtype=int64)

<span style="color:red;font-size:30pt">sonuç: doğruluk değeri = %83.79</span>